[workspace]
members = ["methods", "relay"]

[workspace.dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.17", default-features = false }
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
methods = { path = "./methods", package = "bonsai-starter-methods" }
uniswap_v3_math = { path = "./uniswap-v3-math", package = "uniswap_v3_math" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
