[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests"
ffi = true
fs_permissions = [{ access = 'read', path = '.' }]
optimizer = true
optimizer_runs = 20_000
gas_reports = ["UniswapV3Pool"]
